POST http://localhost:3000/api/tournaments/createPlayer
Content-Type: application/json

{
  "playerName" : "Mr.Great",
      "role" : "batsman",
      "battingStyle" : "right",
      "bowlingStyle" : "right",
      "jerseyNumber" : "2",
      "teamId" : "688842cf139c60cea041f9a2"
}